{{- if and .Values.smtp.secret.create (not .Values.smtp.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-reports.secretName" . }}
  namespace: {{ include "ceph-reports.namespace" . }}
  labels:
    {{- include "ceph-reports.labels" . | nindent 4 }}
  {{- with (include "ceph-reports.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.smtp.keys.url }}: {{ .Values.smtp.secret.url | quote }}
  {{ .Values.smtp.keys.user }}: {{ .Values.smtp.secret.user | quote }}
  {{ .Values.smtp.keys.pass }}: {{ .Values.smtp.secret.pass | quote }}
  {{ .Values.smtp.keys.from }}: {{ .Values.smtp.secret.from | quote }}
  {{ .Values.smtp.keys.to }}: {{ .Values.smtp.secret.to | quote }}
{{- end }}
