{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-reports.serviceAccountName" . }}
  namespace: {{ include "ceph-reports.namespace" . }}
  labels:
    {{- include "ceph-reports.labels" . | nindent 4 }}
  {{- with (merge (deepCopy .Values.serviceAccount.annotations) (fromYaml (include "ceph-reports.annotations" .) | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
